In [1]:
#1. Create a numpy array with numpy.array module and with a data type integer and float.


In [2]:
import numpy as np

In [3]:
arr1 = np.array([20,21,45,70,55.6,77.8])
print(arr1)

[20.  21.  45.  70.  55.6 77.8]


In [4]:
##2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
##Also, print the shape and dimensions of the numpy arrays created above

In [5]:
a = np.array(1)
print("printing the shape of numpy array")
print(a.shape)
print("dimension of the numpy array")
print(a.ndim)

printing the shape of numpy array
()
dimension of the numpy array
0


In [6]:
## one d
arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[1 2 3 4 5 6]
(6,)
1


In [7]:
## two d
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [8]:
### 3 d
arr4 = np.array([[[1,2,3],[4,5,6]]])
print(arr4)
print(arr4.shape)
print(arr4.ndim)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
3


In [11]:
##Four dimensions home task

In [17]:
##3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy

In [18]:
## 2 * 2 matrix
arr1 = np.identity(2)
print(arr1)

[[1. 0.]
 [0. 1.]]


In [21]:
## 3 *3 
arr2 = np.identity(3)
print(arr2)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
## 4 * 4
arr2 = np.identity(4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
print(arr2.dtype)

float64


In [26]:
## convert float into int

In [27]:
arr4= arr2.astype('int')
arr4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [28]:
print(arr4.dtype)

int32


In [29]:
##4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [30]:
arr1 = np.zeros([2,5],dtype = 'int')
print(arr1)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
arr1 = np.zeros([2,5],dtype = 'float')
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
#5. Create a numpy array that has the shape 3x5 and all the elements are 5.

In [34]:
A = np.full([3,5],5)
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [35]:
##6. Create a numpy array with random integers in the range 0-100, and the sample size
##should be 25.


In [36]:
## randint

In [43]:
arr1 =  np.random.randint(0,100, size= 25)
print(arr1)

[16 46 49 82 24 86  1 96 68 43 29 37 16 97 30 13 18 37 14 80 97 52 56 65
 47]


In [47]:
arr1 =  np.random.randint(0,100, size= 5)
print(arr1)

[ 3 22 74 12 66]


In [48]:
#7. Create a numpy array with a shape 3x3 that has all elements as 1.


In [51]:
arr1 = np.full((3,3),1)
print(arr1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [52]:
##8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
##Reshape the array in the shape 3x2 and print the updated shape of the resultant array

In [53]:
arr1 = np.random.randint(0,101,(2,3))
print(arr1)

[[82  1 96]
 [97  7 88]]


In [57]:
arr1 = np.random.randint(0,101,(2,3))
print(arr1)

[[10 14 73]
 [44 90 97]]


In [58]:
print(arr1.reshape(3,2))


[[10 14]
 [73 44]
 [90 97]]


In [59]:
##9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the
#following operations on the same.
#a. Print the first ten elements of the array.


In [75]:
arr1 = np.arange(start= 0 , stop= 1001, step=2)
print(arr1)

[   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386  388  390
  392 

In [76]:
#a. Print the first ten elements of the array.

In [79]:
print(arr1[0:10])

[ 0  2  4  6  8 10 12 14 16 18]


In [80]:
##b. Print the last ten elements of the array


In [91]:
print(arr1[-10:])


[ 982  984  986  988  990  992  994  996  998 1000]


In [92]:
#c. Print the elements from the indexes 10-25

In [93]:
print(arr1[10:26])

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [94]:
#d. Print the element at the index 22


In [96]:
print(arr1[22])

44


In [97]:
#e. Print the array using negative indexing.

In [98]:
print(arr1[::-1])

[1000  998  996  994  992  990  988  986  984  982  980  978  976  974
  972  970  968  966  964  962  960  958  956  954  952  950  948  946
  944  942  940  938  936  934  932  930  928  926  924  922  920  918
  916  914  912  910  908  906  904  902  900  898  896  894  892  890
  888  886  884  882  880  878  876  874  872  870  868  866  864  862
  860  858  856  854  852  850  848  846  844  842  840  838  836  834
  832  830  828  826  824  822  820  818  816  814  812  810  808  806
  804  802  800  798  796  794  792  790  788  786  784  782  780  778
  776  774  772  770  768  766  764  762  760  758  756  754  752  750
  748  746  744  742  740  738  736  734  732  730  728  726  724  722
  720  718  716  714  712  710  708  706  704  702  700  698  696  694
  692  690  688  686  684  682  680  678  676  674  672  670  668  666
  664  662  660  658  656  654  652  650  648  646  644  642  640  638
  636  634  632  630  628  626  624  622  620  618  616  614  612  610
  608 

In [99]:
print(arr1[-1::-1])

[1000  998  996  994  992  990  988  986  984  982  980  978  976  974
  972  970  968  966  964  962  960  958  956  954  952  950  948  946
  944  942  940  938  936  934  932  930  928  926  924  922  920  918
  916  914  912  910  908  906  904  902  900  898  896  894  892  890
  888  886  884  882  880  878  876  874  872  870  868  866  864  862
  860  858  856  854  852  850  848  846  844  842  840  838  836  834
  832  830  828  826  824  822  820  818  816  814  812  810  808  806
  804  802  800  798  796  794  792  790  788  786  784  782  780  778
  776  774  772  770  768  766  764  762  760  758  756  754  752  750
  748  746  744  742  740  738  736  734  732  730  728  726  724  722
  720  718  716  714  712  710  708  706  704  702  700  698  696  694
  692  690  688  686  684  682  680  678  676  674  672  670  668  666
  664  662  660  658  656  654  652  650  648  646  644  642  640  638
  636  634  632  630  628  626  624  622  620  618  616  614  612  610
  608 

In [100]:
##f. Print the last ten elements of the array, using negative indexing.

In [101]:
print(arr1[-10:])

[ 982  984  986  988  990  992  994  996  998 1000]


In [102]:
##10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
##a. Insert the element 6 at the end of the array.


In [103]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [104]:
#a
arr1 = np.append(arr1,6)
print(arr1)

[1 2 3 4 5 6]


In [105]:
#b. Insert the element 10 at the beginning of the array.

In [106]:
arr1 = np.insert(arr1,0,10)
print(arr1)

[10  1  2  3  4  5  6]


In [108]:
##c. Insert the element 30, before 4.


In [109]:
arr1 = np.insert(arr1,4,30)
print(arr1)

[10  1  2  3 30  4  5  6]


In [110]:
##d. Update the element 5 as 50.


In [111]:
arr1[6]=50
print(arr1)

[10  1  2  3 30  4 50  6]


In [112]:
##e. Delete the element 50 in the updated array.


In [113]:
arr1 = np.delete(arr1,6)
print(arr1)

[10  1  2  3 30  4  6]


In [114]:
##f. Create a function to search for the element 30

In [115]:
for i in arr1:
    if i == 30:
        print(i)

30


In [116]:
##g. Sort the array in ascending order

In [117]:
print(np.sort(arr1))

[ 1  2  3  4  6 10 30]
